apiVersion: v1
kind: Service
metadata:
  name: nlpappserv
spec:
  type: NodePort
  selector:
    app: nlpapp-be
  ports:
    - name: nlpapp-port
      protocol: TCP
      targetPort: 3000
      port: 3000